### ISSUE TITLE
最新版がデプロイされているでしょうか？

### ISSUE THREAD

**Issue by daiksy** [cw-shibuya/chatwork-client-gas#6]
いつも便利に使わせていただいています。

postMessageでself_unreadが使いたいと思いまして、確認したところこのp-rがマージされていました。
https://github.com/cw-shibuya/chatwork-client-gas/pull/5

READMEのGoogle App Script スクリプト IDでライブラリを読み込むと、バージョンは18でした。
こちらは、self_unreadのマージが反映されたものでしょうか？

と、いうのも、ライブラリをのバージョン18でself_unreadを指定してsendMessageを実行したところ、どうもこのオプションが有効化されていないようでした（自分のAPIキーでの投稿で未読状態でPOSTされていました）。

ご確認いただけるとうれしいです。

**Comment by cw-shibuya** [comment]
デプロイされていなかったようなので反映しました！

**Comment by daiksy** [comment]
ありがとうございます！未読になりました！！！！
