### ISSUE TITLE
メッセージが既読になる。

### ISSUE THREAD

**Issue by wonder-tsd** [cw-shibuya/chatwork-client-gas#7]
チャットにメッセージを投稿する時に、
self_unreadに1を指定しましたが既読になります。

試しにChatwork APIのページから送信したら未読で届きました。

使い方を間違えてる？
client.sendMessage({
    room_id: '###',
    self_unread: 1,
    body: '***'
 });

**Comment by cw-shibuya** [comment]
@wonder-tsd 
ご連絡ありがとうございます！

確認したところ self_unread に対応したPRはマージしていたんですが、GAS側へのデプロイが漏れていたので先程反映させましたm(_ _)m

**Comment by cw-shibuya** [comment]
手元で確認したところ

```
  client.sendMessage({
    'body': '***',
    'room_id': ***',
    'self_unread': '1' // ← ここに注意
  });
```

 `1` ではなく `'1'` にしないと駄目なようでした

**Comment by wonder-tsd** [comment]
早速の対応ありがとうございます。
OKです未読になりました。
